// Auth Types
export interface User {
  id: string
  email: string
  username?: string
  full_name?: string
  avatar_url?: string
}

// Track Types
export interface Track {
  id: string
  user_id: string
  title: string
  genre: string
  feedback_focus: string[]
  public_url: string
  status: TrackStatus
  uploaded_at: string
  updated_at: string
}

export type TrackStatus = 'pending' | 'matched' | 'reviewed'

// Match Types
export interface Match {
  id: string
  track_a_id: string
  track_b_id: string
  status: MatchStatus
  started_at: string
  completed_at?: string
}

export type MatchStatus = 'pending' | 'active' | 'completed'

// Feedback Types
export interface Feedback {
  id?: string  // Optional because it's auto-generated by Supabase
  match_id: string
  giver_id: string
  receiver_id: string
  content: FeedbackContent
  rating: number
  submitted_at: string
  updated_at: string
}

export interface FeedbackContent {
  overall: string
  mixing?: string
  composition?: string
  creativity?: string
  additional_notes?: string
  rating?: number
}

// Queue Types
export interface QueueEntry {
  trackId: string
  userId: string
  genre: string
  feedbackFocus: string[]
  queuedAt: Date
  priority: number
}

// Upload Types
export interface UploadData {
  file: File | null
  url: string
  title: string
  genre: string
  feedbackFocus: string[]
}

// Profile Types
export interface Profile {
  id: string
  username: string
  full_name: string
  avatar_url: string
  created_at: string
  updated_at: string
}

// API Response Types
export interface ApiResponse<T> {
  data: T | null
  error: string | null
} 